### ISSUE TITLE
Privacy leak

### ISSUE THREAD

**Issue by Kerbas-ad-astra** [KSP-SpaceDock/SpaceDock#128] opened 2016-03-03 03:28 UTC
When a mod updates, the emails expose every subscriber's email address to everyone else subscribing.

**Comment by godarklight** [comment] 2016-03-03 03:48
We thought we fixed this on the 25th (I tested the code directly and it was fine)

I tested it yesterday with an actual testing mod and we were still leaking - it turned out that celery (the task scheduler) was using a cached version of the method that was wrecking our day.

The issue was resolved yesterday via a257a08dc422b57b71c37186793c2e7dbb1bb039, but the commit is only a workaround (it doesn't use the task scheduler any more) - so posting mod updates may end up with a 30 second hang or so if you have many subscribers.

That being said, we've plugged the email leak.

**Comment by Olympic1** [comment] 2016-03-03 12:40
I can confirm that this is now fixed on hotmail accounts as it now shows up as `No receptiants` for me. I don't know for gmail accounts.

**Comment by godarklight** [comment] 2016-03-03 12:49
On gmail accounts the To: field is empty, and if you view the message headers it says ";undisclosed recipients:", so I'm happy to close this.

Apologies for the leak, and especially since the 25th after I thought I had fixed it - only in python can you change a line of code and the changes *not* show up I guess.

**Closed by godarklight** 2016-03-03 12:49 UTC
