### ISSUE TITLE
Full (Optional) Github Integration

### ISSUE THREAD

**Issue by jkoritzinsky** [KSP-SpaceDock/SpaceDock#70] opened 2016-02-18 22:47 UTC
One feature that would be awesome for SpaceDock would be to have full GitHub integration for people who want to use it.  I want to stress that this would be a **totally optional** feature for people to use. Below were some of the features I was thinking of:
- OAuth login via GitHub: People could log in via GitHub like how on other sites people can log in via Google, Twitter, Facebook, etc.
- "Import Mod from GitHub": Show a list of the users GitHub repositories and have them select which repositories to pull releases from a la #33.
- Pull requests like the old KerbalStuff-Bot tied to the user: Have the PRs sent for the mods be sent by the user's GitHub profile instead of the replacement of KerbalStuff-Bot.

This would make it much easier for people who traditionally deploy their mods on GitHub to switch to SpaceDock.

**Comment by avivey** [comment] 2016-02-19 06:04
> OAuth login via GitHub

I've implemented that about 2 weeks ago, in the KS's last pr https://github.com/KerbalStuff/KerbalStuff/pull/129 - just requires activation...

**Comment by avivey** [comment] 2016-02-19 06:11
Another possible integration: if a mod is tied to a GitHub repo, it's possible to have the official download link download directly from GH - savings in bandwidth/disk.

**Comment by jkoritzinsky** [comment] 2016-02-19 17:27
I'd be all for pulling the download from GH directly if it can.  Saves on the bandwidth costs for SpaceDock.

**Comment by godarklight** [comment] 2016-03-03 04:06
I think @V1TA5 has reasons against wanting to use OAuth for login - as he wants to keep everything on his own server, it also complicates dealing with user accounts on spacedock somewhat, but I'm not sure by how much.

That being said, a one click "Import mod from github" does sound nice for those who use github releases when first setting up spacedock, although they'd have to mark which version of KSP each mod is for, which is something that is likely going to break ;)

**Comment by jkoritzinsky** [comment] 2016-03-03 05:10
If @V1TA5 could chime in with why he doesn't want to use OAuth, I'd love to hear the reasoning.  Since the code is already implemented and just needs to be surfaced to the user, it can't be that hard to do.

And the marking of the KSP versions can be done the same way we GitHub mod creators have always done it, manually. Same as CKAN.

Also, note that the only way to do the "Import" button as one button with auto-updating releases is with the GitHub webhooks, which either requires people manually configuring them (definitely not user friendly), or having an OAuth token to do so (at which point, might as well go the whole way).  If the import is not auto-updating, then there really isn't a point to having the import, because then it's just manual dual hosting all over again.

**Comment by HebaruSan** [comment] 2021-11-09 17:33
- OAuth allegedly already implemented in code, just not enabled on site, so no coding needed there
- Copying releases from GitHub is a duplicate of #33 and another issue isn't needed to track the same thing
- The CKAN pull request work flow works fine as-is with the @netkan-bot submitting them, not clear what value would be added by changing the submitter

Closing as no longer needed.

**Closed by HebaruSan** 2021-11-09 17:33 UTC
Labels: Priority: Low, Type: Feature, Status: Need Feedback
