### ISSUE TITLE
SpaceDock serving corrupt zip files

### ISSUE THREAD

**Issue by Shades-McGee** [KSP-SpaceDock/SpaceDock#376] opened 2021-06-26 06:28 UTC
Description (What went wrong?):

SpaceDock's zip files for the following two mods are corrupt...

- Near Future Aeronautics 2.1.0 (spacedock.info, 38.2 MiB)
- Near Future Launch Vehicles 2.1.3 (spacedock.info, 161.3 MiB)

CKAN.InvalidModuleFileKraken: NearFutureAeronautics 2.1.0: C:\Users\First Last\AppData\Local\Temp\tmpD14D.tmp is not a valid ZIP file: Error in step EntryData for GameData/NearFutureAeronautics/Parts/Nacelle/nfa-intake-largecircular.mu: CRC mismatch
   at CKAN.NetModuleCache.Store(CkanModule module, String path, String description, Boolean move)
   at CKAN.NetAsyncModulesDownloader.ModuleDownloadComplete(Uri url, String filename, Exception error)

About to install:

 * Near Future Aeronautics 2.1.0 (spacedock.info, 38.2 MiB)
 * Mark IV Spaceplane System 3.2.0 (cached)
 * Deployable Engines Plugin 1.3.0 (cached)
 * Kerbal Actuators v1.8.3 (cached)
Downloading "https://spacedock.info/mod/1957/Near%20Future%20Aeronautics/download/2.1.0"
Trying to install NearFutureAeronautics 2.1.0, but it's not downloaded or download is corrupted
Error during installation!
If the above message indicates a download error, please try again. Otherwise, please open an issue for us to investigate.
If you suspect a metadata problem: https://github.com/KSP-CKAN/NetKAN/issues/new/choose
If you suspect a bug in the client: https://github.com/KSP-CKAN/CKAN/issues/new/choose

CKAN.InvalidModuleFileKraken: NearFutureLaunchVehicles 2.1.3: C:\Users\First Last\AppData\Local\Temp\tmp4869.tmp is not a valid ZIP file: Error in step EntryData for GameData/NearFutureLaunchVehicles/Parts/Structural/nflv-cargo-tube-75-1.mu: CRC mismatch
   at CKAN.NetModuleCache.Store(CkanModule module, String path, String description, Boolean move)
   at CKAN.NetAsyncModulesDownloader.ModuleDownloadComplete(Uri url, String filename, Exception error)

About to install:

 * Near Future Launch Vehicles 2.1.3 (spacedock.info, 161.3 MiB)
 * Cryogenic Engines 1:2.0.1 (cached)
 * Kerbal Atomics 1:1.2.1 (cached)
 * Deployable Engines Plugin 1.3.0 (cached)
 * Cryo Tanks 1.6.0 (cached)
 * Cryo Tanks Core 1.6.0 (cached)
Downloading "https://spacedock.info/mod/1434/Near%20Future%20Launch%20Vehicles/download/2.1.3"
Trying to install NearFutureLaunchVehicles 2.1.3, but it's not downloaded or download is corrupted
Error during installation!
If the above message indicates a download error, please try again. Otherwise, please open an issue for us to investigate.
If you suspect a metadata problem: https://github.com/KSP-CKAN/NetKAN/issues/new/choose
If you suspect a bug in the client: https://github.com/KSP-CKAN/CKAN/issues/new/choose

Reproduction Steps (What did you do?):

Attempted to install the two mods via CKAN and received the above popup-error/status-log information.

Expected Behavior (What do you think should have happened instead?):

Near Future Exploration/Electrical/Construction/etc. work correctly.

Environment (OS/Browser/Plugins/etc):

Win 10

Extra Information (Screenshots/Error Messages/Javascript Console Output):

@DasSkelett was able to resolve a similar issue earlier...

*quote*

Ha, I found a way to purge the zip from the ATS cache for all users!
We can do it with a curl PURGE request from alpha or beta, apparently ATS doesn't care about where it's coming from.
It should now serve the real, uncorrupted zip:

$ sha256sum Near_Future_Spacecraft-1.4.1.*zip
9392823e6690b412dc2c186df27f7bc226c2742f25d547482f40a5e20bf09360  Near_Future_Spacecraft-1.4.1.cached.zip
bd38e60132d72b3e6e8766eb583681b118f0c3946517711271a39502177fd739  Near_Future_Spacecraft-1.4.1.uncached.zip
bd38e60132d72b3e6e8766eb583681b118f0c3946517711271a39502177fd739  Near_Future_Spacecraft-1.4.1.now.zip

@Shades-McGee, please re-try the installation in CKAN, it should work now.

*end quote*

**Comment by HebaruSan** [comment] 2021-06-26 06:33
Thanks. Duplicate of #375, we don't need new issues just for @DasSkelett to run his script for a few new mods.

**Closed by HebaruSan** 2021-06-26 06:33 UTC

**Comment by Shades-McGee** [comment] 2021-06-26 06:39
Hi @HebaruSan.  Ok, how then should I have reported that I found two additional corrupted zip files, in addition to the one reported in https://github.com/KSP-SpaceDock/SpaceDock/issues/375?
