### ISSUE TITLE
[BUG] Search help obscures the mod page

### ISSUE THREAD

**Issue by Monniasza** [KSP-SpaceDock/SpaceDock#476] opened 2023-03-11 18:17 UTC
Description (What went wrong?):
The mod page is obscured by search help and search bar

Reproduction Steps (What did you do?):
Open any mod page (any game, any mod)

Expected Behavior (What do you think should have happened instead?):
The mod page should be clearly visible, and search help should only show when requested.
The search bar should be shown only on the top bar, and search help should be hidden by default

Environment (OS/Browser/Plugins/etc):
Browser: Chrome 111.0.5563.64
OS: Windows 10 Home

Extra Information (Screenshots/Error Messages/Javascript Console Output):
![image](https://user-images.githubusercontent.com/37037712/224504929-54464ca9-3c6f-4a65-bf3c-114f41f6c5bf.png)

**Comment by HebaruSan** [comment] 2023-03-11 18:18
Duplicate of #473

**Closed by HebaruSan** 2023-03-11 18:18 UTC
