### ISSUE TITLE
Mod description editing

### ISSUE THREAD

**Issue by SerTheGreat** [KSP-SpaceDock/SpaceDock#122] opened 2016-02-29 13:27 UTC
**Description (What went wrong?):**
When entering mod description editor the text's end is cut. Cursor position is inadequate: when moving somewhere and trying to type or copy/paste text, another part of text is edited instead. 
Everything becomes normal only if the text is scrolled down to the bottom.

**Reproduction Steps (What did you do?):**
Sign in.
Goto a mod.
Press Edit this mod.
Try to edit mod's description.

**Expected Behavior (What do you think should have happened instead?):**
Everything is visible and edited at cursor position.

Environment (OS/Browser/Plugins/etc):
Win7/Firefox

**Extra Information (Screenshots/Error Messages/Javascript Console Output):**
The issue experienced when the description text is MarkDown pasted from GitHub and doesn't fit in one scroll page. Example is the description of [this mod](http://www.spacedock.info/mod/244/Hangar%20Grid)

**Comment by ThomasKerman** [comment] 2016-03-03 20:58
To be honest, this sounds more like a browser issue for me, since we are using standard HTML elements, who should not produce this behaviour

**Comment by DasSkelett** [comment] 2020-05-21 23:14
I can't reproduce this (even with Firefox), likely indeed a browser issue, fixed in the meantime.
If you still encounter this problem, please re-open.

**Closed by DasSkelett** 2020-05-21 23:14 UTC
Labels: Priority: Normal, Status: Need Feedback, Type: Bug
