### ISSUE TITLE
Ability to have "Game Admins"

### ISSUE THREAD

**Issue by V1TA5** [KSP-SpaceDock/SpaceDock#223] opened 2019-08-07 20:01 UTC
Game Admins as role who can themselves have mods for that game, can delete/lock mods for that game but cant modify user accounts.

**Comment by HebaruSan** [comment] 2021-11-09 19:25
Duplicate of #211 (game admin would be one of the roles to be added in that request).

**Closed by HebaruSan** 2021-11-09 19:25 UTC
Labels: Priority: Low, Type: Feature
