### ISSUE TITLE
SpaceDock API only supplies 1 author even when 2 are listed

### ISSUE THREAD

**Issue by Dazpoet** [KSP-SpaceDock/SpaceDock#76] opened 2016-02-19 05:46 UTC
...or at least I assume it does since it's the same code as KerbalStuff.

Referencing https://github.com/KerbalStuff/KerbalStuff/issues/112

I'm very sure CKAN would like a heads up in any PR which pokes at this since it might ever so slightly break things on our side.

**Comment by TN-1** [comment] 2016-02-19 08:19
This is something that SirCmpwn confirmed as a bug, Maybe @ThomasKerman can take a look at it

**Comment by EIREXE** [comment] 2016-02-19 14:50
@Dazpoet 08d2f3e fixes this, it adds a new value in the return information "shared_authors" which contain user info for extra authors inside.

**Comment by ThomasKerman** [comment] 2016-02-19 16:19
Closing this since @EIREXE fixed it in #78

**Closed by ThomasKerman** 2016-02-19 16:19 UTC
Labels: bug

**Comment by Dazpoet** [comment] 2016-02-19 17:45
Oh my that was quick :+1:
